### ISSUE TITLE
Cannot read property 'pool' of undefined

### ISSUE THREAD

**Issue by clatronic** [billaue2/cryptonote-aeon-pool#4]
Hey Guys,
when i want start the  `node init.js` this error show.

 TypeError: Cannot read property 'pool' of undefined
    at /home/test/pool/lib/charts.js:148:30
    at IncomingMessage.<anonymous> (/home/test/pool/lib/apiInterfaces.js:31:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

 TypeError: Cannot read property 'pool' of undefined
    at /home/test/pool/lib/charts.js:148:30
    at IncomingMessage.<anonymous> (/home/test/pool/lib/apiInterfaces.js:31:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

TypeError: Cannot read property 'pool' of undefined
    at /home/test/pool/lib/charts.js:154:30
    at IncomingMessage.<anonymous> (/home/test/pool/lib/apiInterfaces.js:31:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

TypeError: Cannot read property 'pool' of undefined
    at /home/test/pool/lib/charts.js:154:30
    at IncomingMessage.<anonymous> (/home/test/pool/lib/apiInterfaces.js:31:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

Thanks

**Comment by m3nt0l** [comment]
It's because you have downloaded another git, not this one:)
Contact me for further help on Skype: drg.style

**Comment by clatronic** [comment]
Oh sry :)
